var iNaturalistAPI = require( "./inaturalist_api" );

module.exports = {
  setConfig: iNaturalistAPI.setConfig,
  annotations: require( "./endpoints/annotations" ),
  comments: require( "./endpoints/comments" ),
  controlled_terms: require( "./endpoints/controlled_terms" ),
  flags: require( "./endpoints/flags" ),
  identifications: require( "./endpoints/identifications" ),
  observation_field_values: require( "./endpoints/observation_field_values" ),
  observations: require( "./endpoints/observations" ),
  photos: require( "./endpoints/photos" ),
  places: require( "./endpoints/places" ),
  posts: require( "./endpoints/posts" ),
  projects: require( "./endpoints/projects" ),
  project_observations: require( "./endpoints/project_observations" ),
  taxa: require( "./endpoints/taxa" ),
  users: require( "./endpoints/users" ),
  Annotation: require( "./models/annotation" ),
  Comment: require( "./models/comment" ),
  ControlledTerm: require( "./models/controlled_term" ),
  Flag: require( "./models/flag" ),
  Identification: require( "./models/identification" ),
  Observation: require( "./models/observation" ),
  ObservationFieldValue: require( "./models/observation_field_value" ),
  Photo: require( "./models/photo" ),
  Place: require( "./models/place" ),
  Post: require( "./models/post" ),
  Project: require( "./models/project" ),
  Taxon: require( "./models/taxon" ),
  User: require( "./models/user" )
};
